---
title: "STAT 380 Final Project"
author: "Tristan Zanowic, Evan Spinney, Julian Sim"
output: html_notebook
---

# Front Matter

## Clear Environment
```{r}
# rm(list = ls())
```

## Library Calls
```{r}
library(tidyverse)
library(Lahman)
library(reshape2)
library(mdsr)
library(mvtnorm)
library(factoextra)
library(cluster)
library(leaps)
library(caret)
library(ISLR2)
library(ggrepel)
```

## Loading Data
```{r}
FullStats <- read.csv("FullStats.csv")
FullStats <-
  FullStats %>%
  rename(deathsper100000 = Deaths...cumulative.total.per.100000.population, casesper100000 = Cases...cumulative.total.per.100000.population)
head(FullStats)
VaccineData <- read.csv("vaccination-data.csv")
FullStats$gdpcap <- FullStats$gdpcap/1000
FullStats$AirTransport <- FullStats$AirTransport/1000
FullStats$HealthExppCap <- FullStats$HealthExppCap/100
```



# Exploratory Data Analysis

## COVID-19 Rates by Geographical Region
```{r}
FullStats %>%
  group_by(WHO.Region) %>%
  summarise(countries = n(), avgcovidcases = mean(totalcases), avgcoviddeaths = mean(totaldeaths), deathrate = (avgcoviddeaths/avgcovidcases))
```

## Exploring Death Rates vs Other Parameters
```{r}
FullStats %>%
  ggplot(aes(x = (gdpcap), y = deathrate, na.rm = TRUE)) +
  geom_point(aes(color = WHO.Region)) 
FullStats %>%
  ggplot(aes(x = (urbpop), y = deathrate, na.rm = TRUE)) +
  geom_point(aes(color = WHO.Region)) 
```

## Identifying Outliers

```{r}
is_outlier <- function(x) {
  return(x < quantile(x, 0.25, na.rm = TRUE) - 1.5 * IQR(x, na.rm = TRUE) | 
             x > quantile(x, 0.75, na.rm = TRUE) + 1.5 * IQR(x, na.rm = TRUE))
}
```

```{r}
temp <- FullStats %>%
    group_by(WHO.Region) %>%
    mutate(outlier = if_else(is_outlier(deathrate), Name, NA_character_),
           outlierBin = is_outlier(deathrate)) 
```


```{r}
# main graph
ggplot(data = temp, aes(x = factor(WHO.Region), y = deathrate, 
                        fill = factor(WHO.Region))) +
    geom_boxplot(aes(color = factor(WHO.Region)), show.legend = FALSE) +
    geom_boxplot(outlier.color = NA) +
    geom_text_repel(aes(label = outlier), nudge_y = 0.01, na.rm = TRUE, 
                    show.legend = FALSE,) +
    theme(
        # label stylings
        axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1),
        plot.title = element_text(size = 15, face = "bold", hjust = 0.5)) +
    theme(
        # legend stylings
        legend.position = c(0.975, 0.95),
        legend.justification = c("right", "top"),
        legend.box.background = element_rect(color = "black")) +
    labs(title = "Death Rate across WHO Regions", 
         x = "Region", y = "Death Rate",
         fill = "Region")
```

## Multiple Linear Regression - Deaths per 100000

```{r}
# All Variables Highyl Significant
deathrate.fit <- lm(data = FullStats, deathsper100000 ~ urbpop + AgeDependancy + HospitalBeds  + gdpcap:PovertyRate + urbpop:HospitalBeds + PovertyRate:HospitalBeds + 0 , na.rm = TRUE)
summary(deathrate.fit)
AIC(deathrate.fit)


```

```{r}
# 34
deathrate.fit <- lm(data = FullStats, deathsper100000 ~ gdpcap + urbpop  + AirTransport + AgeDependancy + MilitaryEx + HospitalBeds + PovertyRate + HealthExppCap  + urbpop:AgeDependancy + gdpcap:PovertyRate + urbpop:HospitalBeds + PovertyRate:HospitalBeds + AirTransport:gdpcap + 0 , na.rm = TRUE)
summary(deathrate.fit)
AIC(deathrate.fit)


library(leaps)
regfit.full = regsubsets(deathsper100000 ~ gdpcap + urbpop  + AirTransport + AgeDependancy + MilitaryEx + HospitalBeds + PovertyRate + HealthExppCap  + urbpop:AgeDependancy + gdpcap:PovertyRate + urbpop:HospitalBeds + PovertyRate:HospitalBeds + PovertyRate:urbpop + gdpcap:HospitalBeds + AgeDependancy:gdpcap + AgeDependancy:PovertyRate + AirTransport:gdpcap + 0 , data = FullStats,  nvmax = 16, method="exhaustive")
summary(regfit.full)

reg.summary <- summary(regfit.full) #get the summary


par(mfrow=c(2,2))
#rss plot - useful
plot(reg.summary$rss ,xlab="Number of Variables ",ylab="RSS",type="l")

#adjr2 plot
plot(reg.summary$adjr2 ,xlab="Number of Variables ", ylab="Adjusted RSq",type="l")
max_adjr2 <- which.max(reg.summary$adjr2)
points(max_adjr2,reg.summary$adjr2[max_adjr2], col="red",cex=2,pch=20)

# AIC criterion (Cp)
plot(reg.summary$cp ,xlab="Number of Variables ",ylab="Cp", type='l')
min_cp <- which.min(reg.summary$cp )
points(min_cp, reg.summary$cp[min_cp],col="red",cex=2,pch=20)

# BIC criterion
plot(reg.summary$bic ,xlab="Number of Variables ",ylab="BIC",type='l')
min_bic <- which.min(reg.summary$bic)
points(min_bic,reg.summary$bic[min_bic],col="red",cex=2,pch=20)
```
```{r}
# 6 is best number of variables
deathrate6.fit <- lm(data = FullStats, deathsper100000 ~ urbpop + HospitalBeds + gdpcap:PovertyRate + urbpop:HospitalBeds + urbpop:PovertyRate + gdpcap:AgeDependancy + 0, na.rm = TRUE)
summary(deathrate6.fit)
AIC(deathrate6.fit)
```


```{r}
#AllModels <- ols_step_all_possible(deathrate.fit)
```


# Multiple Linear Regression - Cases Per 100000
```{r}
# Case Rate - All Vars
caserate.fit <- lm(data = FullStatsNA, casesper100000 ~  gdpcap + urbpop + HealthExppCap + AirTransport + AgeDependancy + MilitaryEx + HospitalBeds + PovertyRate, na.rm = TRUE)
summary(caserate.fit)



```